---
language: python
python:
  # - "2.7"
  - "3.6"

before_install:
 - sudo apt-get update -qq

env:
  # - install_method=source
  - install_method=pip

install:
  # Install requirements.
  - pip install -r ansible-requirements.txt
  #- pip install -r requirements.txt

  # Install latest HEAD of ansible-container from source.
  - |
    if [ "${install_method}" == "source" ]; then
      git clone https://github.com/ansible/ansible-container.git
      cd ansible-container
      pip install -e .[docker]
      cd ..
    fi

  # Install latest stable release of ansible-container from pip.
  - |
    if [ "${install_method}" == "pip" ]; then
      pip install ansible-container[docker]
    fi

cache:
  directories:
  - $HOME/.cache/pip

sudo: required
services:
  - docker

script:
  - ansible-container build --no-container-cache --flatten

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u=${DOCKERHUB_NAME} -p=${DOCKERHUB_PASS};
    export DATETAG=`date +%Y%m%d%H%M%S`;
    docker tag alpine-base-alpine:latest mmaas/base-alpine:${TRAVIS_BUILD_NUMBER};
    docker tag alpine-base-alpine:latest mmaas/base-alpine:${DATETAG};
    docker tag alpine-base-alpine:latest mmaas/base-alpine:latest;
    docker push mmaas/base-alpine:${TRAVIS_BUILD_NUMBER};
    docker push mmaas/base-alpine:${DATETAG};
    docker push mmaas/base-alpine:latest;
    fi; docker images
