# This should be your Ansible playbooks to provision your containers.
# An inventory will be automatically created using the names of the services
# from your container.yml file.
# Add any roles or other modules you'll need to this directory too.
# For many examples of roles, check out Ansible Galaxy: https://galaxy.ansible.com/
#
---
- hosts: all
  gather_facts: false
  tasks:
    - name: Install python
      raw: $(which python) || apk add --no-cache python

- hosts: all
  gather_facts: false
  tasks:
    - name: Install s6 init system
      apk:
        name: s6
        state: present
        update_cache: yes

- hosts: all
  gather_facts: false
  tasks:
    - name: Remove software that is not needed
      apk:
        name: "{{ item }}"
        state: absent
      with_items:
        - python
